version: "3.8"

services:
  # API Gateway
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile.gateway
    container_name: photo-post-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - GATEWAY_SECRET=gateway-secret-key
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - auth
      - users
      - posts
      - likes
    networks:
      - photo-post-network
    restart: unless-stopped

  # Auth Service
  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile.auth
    container_name: photo-post-auth
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - SQLITE_PATH=/data/auth.db
      - REDIS_HOST=redis-auth
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - GATEWAY_SECRET=gateway-secret-key
    volumes:
      - sqlite-auth-data:/data
    depends_on:
      - sqlite-auth
      - redis-auth
      - kafka
    networks:
      - photo-post-network
    restart: unless-stopped

  # Users Service
  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile.users
    container_name: photo-post-users
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - SQLITE_PATH=/data/users.db
      - REDIS_HOST=redis-users
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - GATEWAY_SECRET=gateway-secret-key
    volumes:
      - sqlite-users-data:/data
    depends_on:
      - sqlite-users
      - redis-users
      - kafka
    networks:
      - photo-post-network
    restart: unless-stopped

  # Posts Service
  posts:
    build:
      context: .
      dockerfile: services/posts/Dockerfile.posts
    container_name: photo-post-posts
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - SQLITE_PATH=/data/posts.db
      - REDIS_HOST=redis-posts
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - GATEWAY_SECRET=gateway-secret-key
    volumes:
      - sqlite-posts-data:/data
      - photo-uploads:/app/uploads
    depends_on:
      - sqlite-posts
      - redis-posts
      - kafka
    networks:
      - photo-post-network
    restart: unless-stopped

  # Likes Service
  likes:
    build:
      context: .
      dockerfile: services/likes/Dockerfile.likes
    container_name: photo-post-likes
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - SQLITE_PATH=/data/likes.db
      - REDIS_HOST=redis-likes
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - GATEWAY_SECRET=gateway-secret-key
    volumes:
      - sqlite-likes-data:/data
    depends_on:
      - sqlite-likes
      - redis-likes
      - kafka
    networks:
      - photo-post-network
    restart: unless-stopped

  # SQLite instances
  sqlite-auth:
    image: keinos/sqlite3:latest
    container_name: photo-post-sqlite-auth
    volumes:
      - sqlite-auth-data:/data
    command: ["tail", "-f", "/dev/null"]
    networks:
      - photo-post-network
    restart: unless-stopped

  sqlite-users:
    image: keinos/sqlite3:latest
    container_name: photo-post-sqlite-users
    volumes:
      - sqlite-users-data:/data
    command: ["tail", "-f", "/dev/null"]
    networks:
      - photo-post-network
    restart: unless-stopped

  sqlite-posts:
    image: keinos/sqlite3:latest
    container_name: photo-post-sqlite-posts
    volumes:
      - sqlite-posts-data:/data
    command: ["tail", "-f", "/dev/null"]
    networks:
      - photo-post-network
    restart: unless-stopped

  sqlite-likes:
    image: keinos/sqlite3:latest
    container_name: photo-post-sqlite-likes
    volumes:
      - sqlite-likes-data:/data
    command: ["tail", "-f", "/dev/null"]
    networks:
      - photo-post-network
    restart: unless-stopped

  # Redis instances
  redis-auth:
    image: redis:alpine
    container_name: photo-post-redis-auth
    volumes:
      - redis-auth-data:/data
    ports:
      - "6379:6379"
    networks:
      - photo-post-network
    restart: unless-stopped

  redis-users:
    image: redis:alpine
    container_name: photo-post-redis-users
    volumes:
      - redis-users-data:/data
    ports:
      - "6380:6379"
    networks:
      - photo-post-network
    restart: unless-stopped

  redis-posts:
    image: redis:alpine
    container_name: photo-post-redis-posts
    volumes:
      - redis-posts-data:/data
    ports:
      - "6381:6379"
    networks:
      - photo-post-network
    restart: unless-stopped

  redis-likes:
    image: redis:alpine
    container_name: photo-post-redis-likes
    volumes:
      - redis-likes-data:/data
    ports:
      - "6382:6379"
    networks:
      - photo-post-network
    restart: unless-stopped

  # Single Kafka instance with Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: photo-post-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - photo-post-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: photo-post-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - photo-post-network
    restart: unless-stopped

networks:
  photo-post-network:
    driver: bridge

volumes:
  # SQLite data volumes
  sqlite-auth-data:
    driver: local
  sqlite-users-data:
    driver: local
  sqlite-posts-data:
    driver: local
  sqlite-likes-data:
    driver: local

  # Redis data volumes
  redis-auth-data:
    driver: local
  redis-users-data:
    driver: local
  redis-posts-data:
    driver: local
  redis-likes-data:
    driver: local

  # Single Kafka data volume
  kafka-data:
    driver: local

  # Photo uploads volume
  photo-uploads:
    driver: local
